// Bundles the Three.js addons (GLTFLoader, SkeletonUtils, MeshoptDecoder,
// RoomEnvironment, the post-processing passes) into vendor/three-addons.js.
// r159 ships them only as ES modules, and the page must run from file://
// with plain <script> tags, so they become one IIFE that attaches them to
// the existing window.THREE ('three' is aliased to a shim returning it).
//
//   npm install          (once; the versions are pinned in package.json)
//   node game/tools/build-addons.cjs
'use strict';
const path = require('path'), fs = require('fs');
const esbuild = require('esbuild');
const root = path.join(__dirname, '..', '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'node_modules', 'three', 'package.json'), 'utf8'));

const here = path.join(__dirname, 'three-addons'), out = path.join(__dirname, '..', 'vendor', 'three-addons.js');
if (pkg.version !== '0.159.0') throw new Error('three is ' + pkg.version + ', but vendor/three.min.js is r159: npm install three@0.159.0');

const shim = {
  name: 'three-shim',
  setup(b) {
    // Only the bare 'three' import; 'three/examples/...' are the real files.
    b.onResolve({ filter: /^three$/ }, () => ({ path: path.join(here, 'shim.cjs') }));
  }
};

esbuild.build({
  entryPoints: [path.join(here, 'entry.js')],
  bundle: true, format: 'iife', minify: true, target: 'es2019',
  legalComments: 'none', plugins: [shim], outfile: out,
  define: { __THREE_REVISION__: JSON.stringify(pkg.version.split('.')[1]) },
  banner: { js: '// Generated by game/tools/build-addons.cjs from three@' + pkg.version + ' and esbuild ' + esbuild.version + ' - do not edit. See vendor/README.md.' }
}).then(() => {
  const n = fs.statSync(out).size;
  console.log('wrote vendor/three-addons.js,', (n / 1024).toFixed(0), 'KB');
}).catch(e => { console.error(e.message); process.exit(1); });
