// Writes js/world/models/<id>.js for each compressed model in
// assets/models/dist/, and js/world/models/manifest.js from characters.json.
//
// WebGL refuses anything loaded from a file:// page, and a file:// page
// can't fetch() either, so the models ship as base64 inside scripts, as the
// villain sprites do (embed-sprites.cjs). A model's script is only added to
// the page when the 3D city first needs it (WorldModels.load), so the menu
// doesn't parse megabytes of base64 it never uses.
//
//   node game/tools/embed-models.cjs            every model in dist/
//   node game/tools/embed-models.cjs venom      just one
//
// build-models.cjs runs this after compressing; run it by hand only after
// editing characters.json.
'use strict';
const fs = require('fs'), path = require('path');

const REPO = path.join(__dirname, '..', '..');
const DIST = path.join(REPO, 'game', 'assets', 'models', 'dist');
const MANIFEST = path.join(REPO, 'game', 'assets', 'models', 'characters.json');
const OUT = path.join(REPO, 'game', 'js', 'world', 'models');

function head(src) {
  return '// Generated by tools/embed-models.cjs from ' + src + ' - do not edit.\n';
}

function writeManifest() {
  const json = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  fs.writeFileSync(path.join(OUT, 'manifest.js'), head('assets/models/characters.json') +
    'window.CharacterManifest = ' + JSON.stringify(json, null, 1) + ';\n');
}

function run(ids) {
  fs.mkdirSync(OUT, { recursive: true });
  writeManifest();
  ids = ids && ids.length ? ids : fs.readdirSync(DIST).filter(f => f.endsWith('.glb')).map(f => f.slice(0, -4));
  let total = 0;
  for (const id of ids) {
    if (!/^[a-z0-9_]+$/.test(id)) throw new Error('bad model id ' + id);
    const b = fs.readFileSync(path.join(DIST, id + '.glb'));
    const out = head('assets/models/dist/' + id + '.glb') + "WorldModels.register('" + id + "', '" + b.toString('base64') + "');\n";
    fs.writeFileSync(path.join(OUT, id + '.js'), out);
    total += out.length;
    console.log('wrote js/world/models/' + id + '.js, ' + (out.length / 1e6).toFixed(2) + ' MB');
  }
  console.log('embedded ' + ids.length + ' models, ' + (total / 1e6).toFixed(2) + ' MB of script');
}

if (require.main === module) run(process.argv.slice(2));
module.exports = { run };
