// Writes js/world/villain-sprites.js: the villain PNGs as data URIs.
//
// The 3D city draws the villains with WebGL, and WebGL refuses an image loaded
// from a file:// page (it counts it as cross-origin) - which is how the game
// is opened. A data URI has no origin to object to. Run this again after
// changing a PNG in assets/villains/:
//
//   node game/tools/embed-sprites.cjs
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..'), villains = require('../js/villains.js');
const lines = villains.map(v => '  ' + v.id + ": 'data:image/png;base64," + fs.readFileSync(path.join(root, v.sprite)).toString('base64') + "'");
const out = '// Generated by tools/embed-sprites.cjs from assets/villains/*.png - do not edit.\n' +
  '// WebGL will not take an image loaded from file://, so the 3D sprites are data URIs.\n' +
  'window.VillainSprites = {\n' + lines.join(',\n') + '\n};\n';
fs.writeFileSync(path.join(root, 'js/world/villain-sprites.js'), out);
console.log('wrote js/world/villain-sprites.js,', (out.length / 1024).toFixed(0), 'KB');
