(function(root){'use strict';
 function clamp(v,a,b){return Math.max(a,Math.min(b,v));} function delta(a,b){return (a-b)>>>0;}
 function create(settings){return {pos:{x:.5,y:.5},lastSeq:null,lastMs:null,rateX:0,rateY:0,history:[],blocked:false,settings:settings||{horizontalAxis:'z',verticalAxis:'x',sensitivity:1,invertHorizontal:false,invertVertical:false},source:'mouse'};}
 function center(c){c.pos={x:.5,y:.5};c.rateX=c.rateY=0;c.history=[];}
 function valid(c,p){if(!p||!Number.isInteger(p.seq)||!Number.isInteger(p.ms)||!['gx','gy','gz'].every(k=>Number.isFinite(p[k])&&Math.abs(p[k])<=2500))return false;if(c.lastSeq!==null&&(delta(p.seq,c.lastSeq)===0||delta(p.seq,c.lastSeq)>0x7fffffff))return false;if(c.lastMs!==null&&(delta(p.ms,c.lastMs)===0||delta(p.ms,c.lastMs)>0x7fffffff))return false;return true;}
 function aim(c,p){if(!valid(c,p))return false;var dt=c.lastMs===null?0:delta(p.ms,c.lastMs)/1000;c.lastSeq=p.seq;c.lastMs=p.ms;if(dt>.2){c.rateX=c.rateY=0;return false;}if(!p.armed){c.blocked=true;return false;}if(c.blocked){c.blocked=false;c.rateX=c.rateY=0;return false;}var S=c.settings, hx=p['g'+S.horizontalAxis],vy=p['g'+S.verticalAxis];hx=(S.invertHorizontal?-1:1)*(Math.abs(hx)<.8?0:hx);vy=(S.invertVertical?-1:1)*(Math.abs(vy)<.8?0:vy);var a=dt?1-Math.exp(-dt/.04):1;c.rateX+=(hx-c.rateX)*a;c.rateY+=(vy-c.rateY)*a;if(Math.abs(c.rateX)+Math.abs(c.rateY)>2)c.source='wrist';if(c.source==='wrist'){c.pos.x=clamp(c.pos.x+c.rateX*dt*S.sensitivity/60,0,1);c.pos.y=clamp(c.pos.y+c.rateY*dt*S.sensitivity/60,0,1);}c.history.push({ms:p.ms,x:c.pos.x,y:c.pos.y});while(c.history.length&&delta(p.ms,c.history[0].ms)>300)c.history.shift();return true;}
 function shot(c,p){if(Number.isInteger(p&&p.ms)){var wanted=(p.ms-80)>>>0, found=null;c.history.forEach(x=>{if(delta(wanted,x.ms)<0x80000000)found=x;});if(found){c.pos={x:found.x,y:found.y};}c.blocked=true;c.rateX=c.rateY=0;}return {x:c.pos.x,y:c.pos.y};}
 var api={create:create,center:center,aim:aim,shot:shot,clamp:clamp,delta:delta};if(typeof module!=='undefined')module.exports=api;root.Controller=api;
})(typeof window==='undefined'?globalThis:window);
