(function(){'use strict';var $=id=>document.getElementById(id),stage=$('stage'),ctx=stage.getContext('2d'),images={},state=null,controller=Controller.create(),last=0,effects=[],loadId=0,shownEnd=null;
 function layout(){var r=stage.getBoundingClientRect(),w=r.width,h=r.height;stage.width=w*devicePixelRatio;stage.height=h*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);return {w:w,h:h};}
 function rect(v,w,h){
  var level=LEVELS[state.levelIndex],arena={y:86,h:Math.max(1,h-170)},aspect=images[v.id].naturalWidth/images[v.id].naturalHeight;
  var lead=Math.max(.1,level.approachDuration-level.lungeDuration),approach=Math.min(1,state.approachElapsed/lead);
  var baseHeight=Math.min(arena.h*(.62+.56*approach),w*(.9+.48*approach)/aspect);
  var baseWidth=baseHeight*aspect,baseY=arena.y+arena.h-baseHeight-8;
  var lunge=Math.max(0,Math.min(1,(state.approachElapsed-lead)/level.lungeDuration));
  var rush=1-Math.pow(1-lunge,3),zoom=1+3.1*rush,height=baseHeight*zoom,width=baseWidth*zoom;
  var head=v.targets.find(function(t){return t.name==='HEAD';})||{x:.5,y:.2};
  return {x:((w-width)/2)*(1-rush)+(w*.5-width*head.x)*rush,
    y:baseY*(1-rush)+(h*.34-height*head.y)*rush,width:width,height:height};
 }
 function target(v,sr){var p=v.targets[state.targetIndex%v.targets.length];return{name:p.name,x:sr.x+p.x*sr.width,y:sr.y+p.y*sr.height,radius:Math.max(22,Math.min(38,sr.height*.055))};}
 function draw(now){if(!state)return;var z=layout(),level=LEVELS[state.levelIndex],v=VILLAINS[level.villain],sr=rect(v,z.w,z.h),t=target(v,sr);ctx.clearRect(0,0,z.w,z.h);ctx.globalAlpha=state.mode==='won'?Math.max(0,1-(now-(effects.defeat||now))/800):1;ctx.drawImage(images[v.id],sr.x,sr.y,sr.width,sr.height);ctx.globalAlpha=1;if(state.mode==='playing'){ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(t.x,t.y,t.radius,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#d5222a';ctx.beginPath();ctx.moveTo(t.x-t.radius,t.y);ctx.lineTo(t.x+t.radius,t.y);ctx.moveTo(t.x,t.y-t.radius);ctx.lineTo(t.x,t.y+t.radius);ctx.stroke();var x=controller.pos.x*z.w,y=controller.pos.y*z.h;ctx.strokeStyle='#fff';ctx.beginPath();ctx.arc(x,y,13,0,Math.PI*2);ctx.moveTo(x-20,y);ctx.lineTo(x+20,y);ctx.moveTo(x,y-20);ctx.lineTo(x,y+20);ctx.stroke();effects=effects.filter(e=>now-e.time<500);effects.forEach(e=>{ctx.globalAlpha=1-(now-e.time)/500;ctx.strokeStyle=e.hit?'#fff':'#d5222a';ctx.beginPath();ctx.moveTo(12,z.h-12);ctx.lineTo(e.x,e.y);ctx.stroke();ctx.beginPath();ctx.arc(e.x,e.y,20,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;});}
 $('hud-level').textContent='ENCOUNTER '+level.n;$('hud-vname').textContent=v.name;$('hud-health').textContent=state.health+' / '+state.maxHealth;$('hud-healthbar').style.width=(state.health/state.maxHealth*100)+'%';}
 function frame(now){if(!state){last=now;requestAnimationFrame(frame);return;}var dt=last?Math.min(.1,(now-last)/1000):0;last=now;Combat.tick(state,dt);if(state.mode==='lost'&&shownEnd!=='lost'){shownEnd='lost';card('DEFEAT','Retry','retry');}if(state.mode==='won'&&shownEnd!=='won'){shownEnd='won';effects.defeat=now;card(state.levelIndex<2?'VICTORY':'CITY SAVED',state.levelIndex<2?'Next Encounter':'Replay','next');}draw(now);requestAnimationFrame(frame);}
 function card(title,button,action){
  var c=$('card'),i=$('card-inner');c.classList.remove('is-hidden');i.dataset.kind=title.toLowerCase().replace(/\s+/g,'-');
  var message=title==='INTRO'?'Hit the weak spots before the villain reaches you.':title==='PAUSED'?'The villain stops approaching until you resume.':title==='DEFEAT'?'The villain got too close.':title==='VICTORY'?'One villain down. The city still needs you.':'The city is safe!';
  i.innerHTML='<h2>'+title+'</h2><p>'+message+'</p><div class="card-actions"><button data-action="'+action+'">'+button+'</button><button data-action="menu">MENU</button></div>';
  i.querySelectorAll('button').forEach(b=>b.onclick=()=>{var a=b.dataset.action;if(a==='menu')quit();else if(a==='retry')start(state.levelIndex);else if(a==='next')start(state.levelIndex<2?state.levelIndex+1:0);else{Combat.play(state);c.classList.add('is-hidden');last=performance.now();}});
 }
 function fire(pos){if(!state||state.mode!=='playing')return;var z=layout(),v=VILLAINS[LEVELS[state.levelIndex].villain],t=target(v,rect(v,z.w,z.h)),p={x:pos.x*z.w,y:pos.y*z.h},r=Combat.fire(state,p,t);if(r.accepted){effects.push({x:p.x,y:p.y,hit:r.hit,time:performance.now()});WSAudio.thwip();if(r.hit)WSAudio.crunch();else WSAudio.thunk();}}
 function start(index){state=Combat.start(index,LEVELS);controller=Controller.create(controller.settings);effects=[];shownEnd=null;$('game').classList.remove('is-hidden');$('menu').classList.add('is-hidden');layout();card('INTRO','GO','go');}
 function quit(){$('game').classList.add('is-hidden');$('menu').classList.remove('is-hidden');state=null;document.dispatchEvent(new CustomEvent('webshooter:quit'));}
 function pointer(e){var r=stage.getBoundingClientRect();return{x:Controller.clamp((e.clientX-r.left)/r.width,0,1),y:Controller.clamp((e.clientY-r.top)/r.height,0,1)};}
 stage.addEventListener('pointermove',e=>{controller.pos=pointer(e);controller.source='mouse';});stage.addEventListener('pointerdown',e=>{if(e.button===0){controller.pos=pointer(e);fire(controller.pos);}});window.addEventListener('keydown',e=>{if(!state)return;if(e.code==='Space'){e.preventDefault();fire(controller.pos);}if(e.key==='Escape'){if(state.mode==='playing'){Combat.pause(state);card('PAUSED','RESUME','go');}}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state&&state.mode==='playing'){Combat.pause(state);card('PAUSED','RESUME','go');}});window.addEventListener('resize',layout);
 function preload(){var keys=VILLAINS.map(v=>v.id),n=++loadId;Promise.all(VILLAINS.map(v=>new Promise((ok,bad)=>{var im=new Image();im.onload=()=>im.decode?im.decode().then(()=>ok([v.id,im])).catch(bad):ok([v.id,im]);im.onerror=bad;im.src=v.sprite;}))).then(a=>{if(n!==loadId)return;a.forEach(x=>images[x[0]]=x[1]);window.Game={start:start,quit:quit,get state(){return state},controller:controller,fire:fire};document.dispatchEvent(new CustomEvent('webshooter:ready'));}).catch(()=>alert('Could not load a villain asset. Refresh to retry.'));}preload();requestAnimationFrame(frame);
 window.WebShooterGame={start:start,quit:quit,getController:()=>controller,fire:fire,pause:function(){if(state&&state.mode==='playing'){Combat.pause(state);card('PAUSED','RESUME','go');}},getState:function(){return state;}};})();
