(function () {
  'use strict'; var $=id=>document.getElementById(id), SAVE_KEY='ws.save.v1', SETTINGS_KEY='ws.settings.v2';
  var settings={music:60,sfx:80,muted:false,input:'mouse',sensitivity:1,horizontalAxis:'z',verticalAxis:'x',invertHorizontal:false,invertVertical:false}; $('btn-new').disabled=true;
  try{Object.assign(settings,JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'));}catch(_){}
  function apply(){WSAudio.setMusicVolume(settings.music/100);WSAudio.setSfxVolume(settings.sfx/100);WSAudio.setMuted(settings.muted);$('vol-music').value=settings.music;$('vol-sfx').value=settings.sfx;$('chk-mute').checked=settings.muted;$('input-source').value=settings.input;$('sensitivity').value=settings.sensitivity;$('horizontal-axis').value=settings.horizontalAxis;$('vertical-axis').value=settings.verticalAxis;$('invert-horizontal').checked=settings.invertHorizontal;$('invert-vertical').checked=settings.invertVertical;try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}catch(_){}}
  function write(){settings.music=+$('vol-music').value;settings.sfx=+$('vol-sfx').value;settings.muted=$('chk-mute').checked;settings.input=$('input-source').value;settings.sensitivity=+$('sensitivity').value;settings.horizontalAxis=$('horizontal-axis').value;settings.verticalAxis=$('vertical-axis').value;settings.invertHorizontal=$('invert-horizontal').checked;settings.invertVertical=$('invert-vertical').checked;var c=WebShooterGame.getController();c.settings=settings;c.source=settings.input;apply();}
  document.addEventListener('webshooter:ready',()=>{apply();$('btn-new').disabled=false;var c=WebShooterGame.getController();c.settings=settings;c.source=settings.input;var link=new ShooterLink();link.on('status',s=>{$('menu-status').textContent='CONTROLLER: '+s.toUpperCase();$('controller-status').textContent=s==='legacy'?'Connected, but firmware needs an update for aiming.':'Controller '+s;});link.on('reconnect',()=>{var c=WebShooterGame.getController();c.lastSeq=c.lastMs=null;});link.on('aim',p=>Controller.aim(WebShooterGame.getController(),p));link.on('shoot',p=>WebShooterGame.fire(Controller.shot(WebShooterGame.getController(),p)));link.connect();});
  $('btn-new').onclick=()=>{WSAudio.init();WSAudio.startMusic();try{localStorage.setItem(SAVE_KEY,JSON.stringify({chapter:1,savedAt:new Date().toISOString()}));}catch(_){}WebShooterGame.start(0);};$('btn-continue').onclick=()=>{try{var s=JSON.parse(localStorage.getItem(SAVE_KEY));WebShooterGame.start(Math.max(0,Math.min(2,(s.chapter||1)-1)));}catch(_){}};$('btn-settings').onclick=()=>{WebShooterGame.pause();$('settings').classList.remove('is-hidden');};$('btn-close').onclick=()=>$('settings').classList.add('is-hidden');$('btn-center').onclick=()=>Controller.center(WebShooterGame.getController());window.addEventListener('keydown',e=>{if(e.key==='c'||e.key==='C')Controller.center(WebShooterGame.getController());});['vol-music','vol-sfx','input-source','sensitivity','horizontal-axis','vertical-axis','chk-mute','invert-horizontal','invert-vertical'].forEach(id=>$(id).onchange=write);try{$('btn-continue').disabled=!JSON.parse(localStorage.getItem(SAVE_KEY));}catch(_){}
})();
